[package]
name = "rug"
version = "0.2.1"
authors = ["sts10 <sschlinkert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
csv = "1"
structopt = "0.3"
